# Generated by Django 4.2.4 on 2023-08-04 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(unique=True)),
                ('short_code', models.CharField(max_length=6, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2023, 9, 3, 16, 47, 36, 848654))),
            ],
        ),
    ]
