# Generated by Django 4.2.4 on 2023-08-04 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 3, 17, 23, 39, 151911)),
        ),
    ]
